[project]
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi-vscode"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
install = "yarn install"
pretest = { cmd = "yarn run pretest", depends_on = ["install"] }
test = {cmd = "yarn run test", depends_on = ["pretest"]}
package = {cmd = "vsce package --no-yarn"}

[dependencies]
nodejs = ">=22.9.0,<22.10"
yarn = ">=4.5.1,<5"

